import investment.portofolio.AssetManager;
import investment.portofolio.Building;
import investment.portofolio.Jewel;
import investment.portofolio.Vehicle;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Application {
    public static void main(String[] args) {
        Building h1 = new Building("House 1", 27, 9);
        Building h2 = new Building("House 2", 10, 24);
        Building h3 = new Building("House 3", 17, 5);
        Vehicle c0 = new Vehicle("Car 1", 32, 8);
        Vehicle c1 = new Vehicle("Car 1", 8, 4);
        Vehicle c2 = new Vehicle("Car 2", 16, 3);
        Jewel ring = new Jewel("Ring 1", 24);

        AssetManager manager = new AssetManager();
        manager.add(h1, h2, h3);
        manager.add(c0, c1, c2);
        manager.add(ring);
        manager.getItems().clear();

        System.out.println("Items sorted by the name: " + manager.getItems());
        System.out.println("Assets sorted by the profit: " + manager.getAssets());
    }
}